package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private String name;
    private int age;
    private boolean premiumMember;
    private int transactionCountLastMonth;
    private double averageTransactionValue;
    private String recommendation;
    private boolean silentMode;


    // Constructor
    public Customer(String name, int age, boolean premiumMember, 
                    int transactionCountLastMonth, double averageTransactionValue,
                    boolean silentMode) {
        this.name = name;
        this.age = age;
        this.premiumMember = premiumMember;
        this.transactionCountLastMonth = transactionCountLastMonth;
        this.averageTransactionValue = averageTransactionValue;
        this.recommendation = "";
        this.silentMode = silentMode;
    }

    // Getters and Setters
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }

    public boolean isPremiumMember() { return premiumMember; }
    public void setPremiumMember(boolean premiumMember) { this.premiumMember = premiumMember; }

    public int getTransactionCountLastMonth() { return transactionCountLastMonth; }
    public void setTransactionCountLastMonth(int count) { this.transactionCountLastMonth = count; }

    public double getAverageTransactionValue() { return averageTransactionValue; }
    public void setAverageTransactionValue(double value) { this.averageTransactionValue = value; }

    public String getRecommendation() { return recommendation; }
    public void setRecommendation(String recommendation) { this.recommendation = recommendation; }
    
    public boolean isSilentMode() { return silentMode; }
    public void setSilentMode(boolean silentMode) { this.silentMode = silentMode; }
}
