package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private String orderId;
    private Customer customer;
    private double orderValue;
    private boolean expeditedShipping;
    private int itemsCount;
    private String recommendation;
    private boolean silentMode;


    // Constructor
    public Order(String orderId, Customer customer, double orderValue, 
                 boolean expeditedShipping, int itemsCount, boolean silentMode) {
        this.orderId = orderId;
        this.customer = customer;
        this.orderValue = orderValue;
        this.expeditedShipping = expeditedShipping;
        this.itemsCount = itemsCount;
        this.recommendation = "";
        this.silentMode = silentMode;
    }

    // Getters and Setters
    public String getOrderId() { return orderId; }
    public void setOrderId(String orderId) { this.orderId = orderId; }

    public Customer getCustomer() { return customer; }
    public void setCustomer(Customer customer) { this.customer = customer; }

    public double getOrderValue() { return orderValue; }
    public void setOrderValue(double value) { this.orderValue = value; }

    public boolean isExpeditedShipping() { return expeditedShipping; }
    public void setExpeditedShipping(boolean expedited) { this.expeditedShipping = expedited; }

    public int getItemsCount() { return itemsCount; }
    public void setItemsCount(int count) { this.itemsCount = count; }

    public String getRecommendation() { return recommendation; }
    public void setRecommendation(String recommendation) { this.recommendation = recommendation; }

    public boolean isSilentMode() { return silentMode; }
    public void setSilentMode(boolean silentMode) { this.silentMode = silentMode; }
    
}